#!/bin/sh
HOME=/home/nafaryus
GUNICORN=gunicorn
ROOT=${HOME}/projects/elnafo
PID=${ROOT}/logs/gunicorn.pid
LOG=${ROOT}/logs/gunicorn.log
LEVEL=DEBUG

APP=app:app
BIND="127.0.0.1:5000"

if [ -f $PID ]; then rm $PID; fi

cd $ROOT
. ${ROOT}/env/bin/activate && exec $GUNICORN --bind $BIND --pid=$PID --log-file $LOG --log-level $LEVEL --reload $APP
